apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: gitops-test-ns
spec:
  sourceFormat: unstructured
  git:
    repo: "https://github.com/ranjithramadas-g/cc-cluster"
    branch: "main"
    dir: "gitops-test-ns" # This is the folder the RepoSync will watch
    auth: "none"
